feat: fetchin salons and single salon; adding salon to favorites; adding opinion to salon
Voirsy/back-end pull request #11
Opened 2021-12-10 20:18 UTC by lzawistowsky

close #9

2021-12-11 12:15 UTC, zawolanski requested changes
Except for a few things, everything is fine.

2021-12-11 12:15 UTC, zawolanski commented on controllers/salons.js
> +        const city = req.body.city
According to the documentation, there should be `req.body.location`.

2021-12-11 12:15 UTC, zawolanski commented on controllers/salons.js
> +            error.statusCode = 500
I think `400` is more appropriate.

2021-12-18 12:51 UTC, pawelsobkowski reviewed
I think, I have nothing to add

2021-12-19 14:25 UTC, merged